services:
  api:
    image: docker.hyeonwoo.com/goormdotcom/api-v1:test
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev,secret
    volumes:
      - ./config:/app/config
    user: 1000:1000
