services:
  app:
    image: goormdotcom-order-service:latest
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 8082:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev,secret
    volumes:
      - ./config:/app/config
    user: 1000:1000

  goormdotcom-db-order-service:
    image: postgres:16
    container_name: goormdotcom-db-order-service
    ports:
      - 5235:5432
    environment:
      POSTGRES_DB: goormdotcom
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app