spring:
  application:
    name: "order-service"
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    url: jdbc:postgresql://hyeonwoo.com:5234/goormdotcom?currentSchema=public
    username: goorm1
    password: goorm123

  # JPA 설정 (프로파일별로 오버라이드 가능)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 200
        format_sql: true

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: never

springdoc:
  use-fqn: true

server:
  port: ${PORT:5232}

service:
  user:
    url: http://localhost:8080
  product:
    url: http://localhost:8080
  order:
    url: http://localhost:8080
  payment:
    url: http://localhost:8080
  delivery:
    url: http://localhost:8080
  stock:
    url: http://localhost:8080

logging:
  level:
    root: INFO
    profect.group1.goormdotcom: INFO

